config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/myalbum'
  resources :albums
  devise_for :users
  get 'pages/index'
  get 'pages/about'
  

  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  mount_uploader :avtar, AvtarUploader

  has_many :albums, dependent: :destroy

  validates_presence_of :avtar,:name

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:image, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include DeviseWhitelist

end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern
 
    included do
       before_action :configure_permitted_parameters, if: :devise_controller?
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:avtar, :name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:avtar, :name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def index

  end

  def about
  end

  def myalbum
    @albums = Album.where(user_id: current_user.id)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true, html: {multipart: true}) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<div class="row">

    <% @albums.each do |album| %>


        <!-- start jumbo -->
        <div class="jumbotron col-md-3" style="margin: 1px" >
            <%=image_tag(album.image_url, class: 'img-thumbnail img-fluid') %>
            <p class="lead">
            Owner:  <%= album.user.name %>
            </p>
            <hr class="my-4">
            <p>
              <%= album.description %>
            </p>
        </div>
    <!-- jumbo... -->
    <% end %>
</div>
    
      
      
      
      

 

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @album.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageAlbum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">

    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>

      <%= render "shared/navbar" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<% if current_user != nil %>
    <%= image_tag current_user.avtar_url, class: 'profile-img' %>
<% end %>

app/views/pages/myalbum.html.erb
<p id="notice"><%= notice %></p>

<h1>My Albums</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%=image_tag(album.image_url, class: 'profile-img' )%></td>
        <td><%= album.description %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">ImageAlbum</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', pages_index_path, class: 'nav-link active' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', pages_about_path, class: 'nav-link active' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Albums', albums_path, class: 'nav-link active' %>
      </li>
      <%if current_user %>
        <li class="nav-item">
          <%= link_to 'My_Albums', pages_myalbum_path, class: 'nav-link active' %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <% if current_user %>
          <%= link_to "LogOut",destroy_user_session_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0"%>   
      <% else %>
          <%= link_to "Log_In",new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0"%>  
      <% end %>
    </form>
  </div>
</nav>